import type { Thought } from "@/lib/thoughts-types";

export const thought: Thought = {
  slug: "cookies-arent-canceled-heres-why-that-doesnt-matter",
  title: "Cookies Aren't Canceled — Here's Why That Doesn't Matter.",
  date: "2024-08-14",
  excerpt:
    "Google didn't kill the cookie, but 70%+ of US internet traffic is already cookieless one way or another. Owning your first-party audience is the only durable strategy — independent of what Google decides next.",
  linkedinUrl:
    "https://www.linkedin.com/pulse/cookies-arent-canceled-heres-why-doesnt-matter-amol-waishampayan-dlq3e",
  coverImage: "/thoughts/cookies-arent-canceled.jpg",
  coverAlt: "Image generated by ChatGPT 4o",
  body: `There are two keys to thriving in the digital world: Owning your audience data and effectively utilizing it.

The truth: cookies were never going to go away in a big apocalyptic bang. No fall of the Berlin wall, no closing bell of the stock market, no CTRL+ALT+DELETE where you could "End Task" in an executioner style move. The decay and signal loss across BOTH third-party cookies and MobileIDs started years ago and gained a life of its own. That systemic disruption snowballed to a place where no one party can control its outcome and stop its trajectory (including Google itself!). Some quick stats to keep ourselves grounded:

- As of July 2024, Chrome has 51.07% market share in the US (down 2 points from Sept 2023) = at least 49% of the remaining US internet already has 3p cookies removed off the bat and the number is growing.
- Furthermore, 40% of Chrome users choose to voluntarily disable third party cookies going into their Settings = an updated 70%+ of the US internet already has 3p cookies removed
- Google Proposed a NEW 3p Cookie Opt-in per site = many users will disable cookies when given a choice (think "Ask App Not to Track" from Apple, which infamously crippled facebook with a 35% opt-in rate)

The moneyline bet on whether Google would ever drop the proverbial cookie axe was heavily favored to be a NO by true industry experts.

You know what else has the same odds by true industry experts? Owning your first party audience data and investing in the right tools to effectively activate will be the winning strategy in 2024 and beyond.

Our northstar compass at [fullthrottle.ai®](https://www.linkedin.com/company/fullthrottle) is to build easy to use ad technology that is enhanced with buyer + seller 1p data. So easy a Caveman can do it! Delivering our 'out of box' streamlined solution means our agencies and advertisers achieve independence and resiliency from the systemic fracking that continues to unfold across adtech. Simply put, if you are in control of your own audience, you are in control of your destiny (well...marketing wise anyway).

So, in essence, this moment is not memorable, Google's announcement doesn't really change that much, and you should stay focused on controlling your means to execute easy, effective, targeted, measurable advertising in a cookieless manner.

Ps – this is what [fullthrottle.ai](https://fullthrottle.ai) enables for brands, agencies, and media companies.`,
};
